# Generated by Django 5.1.1 on 2024-10-17 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receiver_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('blood', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+')], max_length=3)),
                ('hospital', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=10)),
                ('Receiver_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.receiver')),
            ],
        ),
    ]
