# Generated by Django 5.1.1 on 2024-10-29 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_receiver_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiver_request',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
